export const Action = Object.freeze({

  // User & HR
  VIEW_PENDING_USERS: "VIEW_PENDING_USERS",
  APPROVE_USER: "APPROVE_USER",
  REJECT_USER: "REJECT_USER",

  // Leave
  APPLY_LEAVE: "APPLY_LEAVE",
  VIEW_LEAVE: "VIEW_LEAVE",
  APPROVE_LEAVE: "APPROVE_LEAVE",
  OVERRIDE_LEAVE: "OVERRIDE_LEAVE",

  // Attendance
  MARK_ATTENDANCE: "MARK_ATTENDANCE",
  VIEW_ATTENDANCE: "VIEW_ATTENDANCE",
  OVERRIDE_ATTENDANCE: "OVERRIDE_ATTENDANCE",


  // WeeklyOff
  MANAGE_WEEKLY_OFF: "MANAGE_WEEKLY_OFF",
});
